version: '3'
services:
  backend:
    image: qnib/plain-elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    deploy:
      resources:
        # Only one master for now
        replicas: 1
        limits:
          cpus: '1'
          memory: 768M
      update_config:
        parallelism: 1
        delay: 15s
      restart_policy:
        condition: on-failure
    environment:
      ES_HEAP_MAX: "512m"
      ES_HEAP_MIN: "512m"
      ES_NODE_MASTER: "true"
      ES_NODE_DATA: "true"
  frontend:
    image: qnib/plain-kibana5
    ports:
      - "5601:5601"
    deploy:
      resources:
        replicas: 1
        limits:
          cpus: '1'
          memory: 512M
      update_config:
        parallelism: 1
        delay: 15s
    environment:
        ES_MASTER_HOST: qwatch-ng_backend
  collector:
    image: qnib/qwatch-ng
    deploy:
      resources:
        replicas: 1
        limits:
          cpus: '0.25'
          memory: 128M
    environment:
      ES_MASTER_HOST: qwatch-ng_backend
